-- AlterTable
ALTER TABLE "BillPeriod" ADD COLUMN     "billingCycleType" TEXT NOT NULL DEFAULT 'MONTHSARY',
ADD COLUMN     "elecRateUsed" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN     "isProrated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lateFeeApplied" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "waterRateUsed" DOUBLE PRECISION NOT NULL DEFAULT 50.0;

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "leaseStartDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "BillingConfig" (
    "id" TEXT NOT NULL DEFAULT 'global',
    "waterRate" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
    "elecRate" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
    "billingCycle" TEXT NOT NULL DEFAULT 'MONTHSARY',
    "lateFeeImposed" BOOLEAN NOT NULL DEFAULT false,
    "lateFeeAmount" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BillingConfig_pkey" PRIMARY KEY ("id")
);
